"""Out-of-distribution check on WBM (the Matbench Discovery test set).

MACE-MP-0 was trained on MPtrj (Materials Project), so scores on MP materials overstate accuracy
on genuinely new materials. WBM structures were generated by elemental substitution into MP
prototypes and relaxed with DFT; they are not in MP/MPtrj. We draw a fixed-seed random sample of
300 from WBM's unique-prototype subset (215,488 rows whose prototype is neither in MP nor
duplicated within WBM — the subset Matbench Discovery scores), relax the UNRELAXED WBM structure
with MACE, and score:

  energy     E_MACE/atom vs WBM's uncorrected DFT energy/atom (MP-compatible PBE/PBE+U settings)
  stability  e_hull_pred = e_hull_DFT + (E_MACE - E_DFT)/atom — the Matbench Discovery construction.
             Valid because the MP2020 correction per atom (shipped per row by WBM) is identical for
             the MACE and DFT entries of the same composition, and the MP hull is unchanged.

This is the out-of-distribution analogue of stability mode (a); it is always reported separately
from the in-distribution (MP) scores.
"""

from __future__ import annotations

import gzip
import json
import logging
import re

import numpy as np
import pandas as pd
from pymatgen.core import Composition, Structure

from harness import compare, store
from harness.config import DATA_DIR, EXTERNAL_CACHE_DIR, settings_tag
from harness.jobs import relax_job
from harness.platform_check import core_counts
from harness.runner import run_pool

log = logging.getLogger(__name__)

SUITE = "ood"
WBM_DIR = EXTERNAL_CACHE_DIR / "wbm"
SUMMARY = WBM_DIR / "2023-12-13-wbm-summary.csv.gz"
INIT_STRUCTS = WBM_DIR / "2022-10-19-wbm-init-structs.jsonl.gz"
SAMPLE_FILE = DATA_DIR / "ood_wbm_sample.json"
SAMPLE_STRUCTS = WBM_DIR / "ood_sample_init_structs.json"
N_SAMPLE = 300
SEED = 20260910
SOURCE = "WBM via Matbench Discovery data files, figshare doi:10.6084/m9.figshare.22715158 (v37)"
THRESHOLDS = (0.0, 0.1)
ON_HULL_TOL = 1e-6
LARGE_CELL_ATOMS = 100
REQUIRED = ["uncorrected_energy_from_cse", "n_sites", "e_above_hull_mp2020_corrected_ppd_mp",
            "e_form_per_atom_mp2020_corrected", "e_correction_per_atom_mp2020"]
ID_RE = re.compile(r'"material_id"\s*:\s*"([^"]+)"')


def predict_e_hull(each_true: float, e_mace: float, e_dft: float) -> float:
    """Matbench Discovery: shift the DFT hull distance by the model-DFT energy difference (eV/atom)."""
    return each_true + (e_mace - e_dft)


def sample_ids(df: pd.DataFrame, n: int = N_SAMPLE, seed: int = SEED) -> list[str]:
    pool = df[(df["unique_prototype"] == True) & df[REQUIRED].notna().all(axis=1)]  # noqa: E712
    return pool.sample(n=min(n, len(pool)), random_state=seed)["material_id"].tolist()


def load_summary() -> pd.DataFrame:
    return pd.read_csv(SUMMARY)


def sample_file(n: int = N_SAMPLE):
    return SAMPLE_FILE if n == N_SAMPLE else DATA_DIR / f"ood_wbm_sample_{n}.json"


def sample_structs_path(n: int = N_SAMPLE):
    return SAMPLE_STRUCTS if n == N_SAMPLE else WBM_DIR / f"ood_sample_{n}_init_structs.json"


def load_sample(summary: pd.DataFrame, n: int = N_SAMPLE) -> list[str]:
    path = sample_file(n)
    if path.is_file():
        return json.loads(path.read_text())["ids"]
    ids = sample_ids(summary, n=n)
    path.write_text(json.dumps({
        "source": SOURCE, "pool": "unique_prototype == True with required columns present",
        "pool_size": int(((summary["unique_prototype"] == True) & summary[REQUIRED].notna().all(axis=1)).sum()),  # noqa: E712
        "n": len(ids), "seed": SEED, "method": "pandas.DataFrame.sample(random_state=seed)", "ids": ids}, indent=1) + "\n")
    return ids


def load_structures(ids: list[str], cache_file=SAMPLE_STRUCTS) -> dict[str, Structure]:
    """Initial (unrelaxed) WBM structures for the sample; scanned once, then cached in cache_file."""
    if cache_file.is_file():
        raw = json.loads(cache_file.read_text())
    else:
        wanted, raw = set(ids), {}
        with gzip.open(INIT_STRUCTS, "rt") as fh:
            for line in fh:
                m = ID_RE.search(line[:200])
                if m and m.group(1) in wanted:
                    d = json.loads(line)
                    raw[d["material_id"]] = d["initial_structure"]
                    if len(raw) == len(wanted):
                        break
        cache_file.write_text(json.dumps(raw))
    missing = set(ids) - set(raw)
    if missing:
        log.warning("%d sampled ids have no initial structure: %s", len(missing), sorted(missing)[:5])
    return {k: Structure.from_dict(v) for k, v in raw.items()}


# DFT-relaxed WBM structures + calculation parameters (run type, U values, POTCARs), md5-checked on download.
CSE_FILE = WBM_DIR / "2022-10-19-wbm-computed-structure-entries.jsonl.gz"
CSE_MD5 = "655b7a9c368e136dd8747f1ef8002e7a"  # figshare file 53161832 (Matbench Discovery data files)


def load_entries(ids: list[str], cache_file=None) -> dict:
    """WBM ComputedStructureEntries (DFT-relaxed) for the given ids; scanned once, then cached."""
    from pymatgen.entries.computed_entries import ComputedStructureEntry

    cache_file = cache_file or WBM_DIR / f"cse_{len(ids)}_{compare.stable_seed(','.join(sorted(ids))):08x}.json"
    if cache_file.is_file():
        raw = json.loads(cache_file.read_text())
    else:
        if not CSE_FILE.is_file():
            raise FileNotFoundError(f"{CSE_FILE} missing — see README (figshare doi:10.6084/m9.figshare.22715158)")
        wanted, raw = set(ids), {}
        with gzip.open(CSE_FILE, "rt") as fh:
            for line in fh:
                m = ID_RE.search(line[:200])
                if m and m.group(1) in wanted:
                    raw[m.group(1)] = json.loads(line)["computed_structure_entry"]
                    if len(raw) == len(wanted):
                        break
        cache_file.write_text(json.dumps(raw))
    missing = set(ids) - set(raw)
    if missing:
        log.warning("%d ids have no WBM computed structure entry: %s", len(missing), sorted(missing)[:5])
    return {k: ComputedStructureEntry.from_dict(v) for k, v in raw.items()}


def retry_jobs(compute: dict, tag: str, done: set | frozenset = frozenset()) -> list[dict]:
    """Fallback-ladder jobs for WBM relaxations rejected by the convergence / sanity guard (not for
    composition mismatches), restarting the perturbed rung from the WBM initial structure."""
    from harness.config import LADDER_BUDGET_S

    todo = {key: pl for key, pl in store.load_payloads(SUITE, tag=tag).items()
            if "each_pred" in pl and "ladder" not in pl and compare.recheck(pl.get("rejection"), pl)
            and key.replace(f"@{tag}", f":ladder@{tag}") not in done}
    if not todo:
        return []
    ids = sorted(pl["wbm_id"] for pl in todo.values())
    starts = load_structures(ids, cache_file=WBM_DIR / f"ladder_init_{compare.stable_seed(','.join(ids)):08x}.json")
    summary = load_summary().set_index("material_id")
    jobs = []
    for key, pl in todo.items():
        wid = pl["wbm_id"]
        jobs.append({"job_key": key.replace(f"@{tag}", f":ladder@{tag}"), "record_key": key, "job_fn": "ladder",
                     "wbm_id": wid, "ref": {k: (v.item() if hasattr(v, "item") else v) for k, v in summary.loc[wid].to_dict().items()},
                     "rung1": pl, "rung1_rejection": compare.recheck(pl.get("rejection"), pl),
                     "original": starts.get(wid, pl["relaxed"]),
                     "seed": compare.stable_seed(key), "structure": pl["relaxed"], "budget_s": LADDER_BUDGET_S,
                     "device": compute["device"], "dtype": compute["dtype"]})
    return jobs


def _record_static(job: dict, res: dict) -> None:
    """Single-point MACE energy at WBM's DFT-relaxed structure: the model's energy error with no
    relaxation in the way (key '<id>:static@<tag>')."""
    ref, key, wid = job["ref"], job["job_key"], job["wbm_id"]
    if res.get("status") != "ok":
        store.record_job(SUITE, key, res["status"], payload={"wbm_id": wid, "kind": "static"}, error=res.get("error"))
        return
    e_dft = ref["uncorrected_energy_from_cse"] / ref["n_sites"]
    d = res["energy_per_atom"] - e_dft
    store.record_results([{"suite": SUITE, "job_key": key, "structure": f"{wid} [static]", "formula": ref["formula"],
                           "family": "wbm-unique-prototype", "units": "eV/atom", "test": "static:energy_per_atom",
                           "simulated_value": res["energy_per_atom"], "reference_value": e_dft, "error_abs": d,
                           "reference_provenance": "wbm_computed", "settings": res["metadata"],
                           "reference_source": f"{wid} uncorrected DFT energy; MACE single point at the DFT-relaxed structure, {SOURCE}"}])
    store.record_job(SUITE, key, "ok", payload={"wbm_id": wid, "kind": "static", "e_static": res["energy_per_atom"],
                                                "de_static_mev": d * 1000}, settings=res["metadata"], runtime_s=res.get("wall_time_s"))


def _record_ladder(job: dict, res: dict) -> None:
    r1 = job["rung1"]
    summary1 = {k: r1.get(k) for k in ("e_mace", "converged", "n_steps", "wall_time_s")} | {"rejection": job["rung1_rejection"]}
    if res.get("status") == "ok":
        _record({**job, "job_key": job["record_key"], "job_fn": "relax",
                 "payload_extra": {"rung": res.get("rung"), "ladder": res.get("ladder", []), "rung1": summary1}}, res)
    else:
        store.record_job(SUITE, job["record_key"], "ok",
                         payload={**r1, "rung": None, "ladder": [], "ladder_error": res.get("error"), "rung1": summary1})
    store.record_job(SUITE, job["job_key"], res.get("status", "failed"),
                     payload={"wbm_id": job["wbm_id"], "ladder_of": job["record_key"], "rung": res.get("rung")},
                     error=res.get("error"), runtime_s=res.get("job_wall_s"))


def _record(job: dict, res: dict) -> None:
    if job.get("job_fn") == "ladder":
        _record_ladder(job, res)
        return
    if job.get("job_fn") == "static":
        _record_static(job, res)
        return
    ref, key, wid = job["ref"], job["job_key"], job["wbm_id"]
    if res.get("status") != "ok":
        store.record_job(SUITE, key, res["status"], payload={"wbm_id": wid}, error=res.get("error"),
                         runtime_s=res.get("job_wall_s"), settings={"layout": job.get("layout")})
        log.warning("%s %s: %s", wid, res["status"], res.get("error"))
        return
    relaxed = res["relaxed"]
    e_dft = ref["uncorrected_energy_from_cse"] / ref["n_sites"]
    e_mace = res["energy_per_atom"]
    d = e_mace - e_dft
    each_true = ref["e_above_hull_mp2020_corrected_ppd_mp"]
    each_pred = predict_e_hull(each_true, e_mace, e_dft)
    e_form_true = ref["e_form_per_atom_mp2020_corrected"]
    rejection = compare.rejection_reason(res, reference_per_atom=e_dft)
    comp_ok = relaxed.composition.reduced_composition == Composition(ref["formula"]).reduced_composition
    if not comp_ok:
        rejection = rejection or f"composition mismatch ({relaxed.composition.reduced_formula} vs {ref['formula']})"
    flags = {**compare.system_flags(relaxed.composition.elements), "rejection": rejection,
             "converged": res["converged"], "n_steps": res["n_steps"], "max_stress_gpa": res["max_stress_gpa"]}
    base = {"suite": SUITE, "job_key": key, "structure": f"{wid} {relaxed.composition.reduced_formula}",
            "formula": relaxed.composition.reduced_formula, "family": "wbm-unique-prototype", "units": "eV/atom",
            "reference_provenance": "wbm_computed", "flags": flags,
            "settings": res["metadata"] | {"layout": job.get("layout")}, "runtime_s": res["wall_time_s"]}
    store.record_results([
        {**base, "test": "energy_per_atom", "simulated_value": e_mace, "reference_value": e_dft, "error_abs": d,
         "reference_source": f"{wid} uncorrected DFT energy (from CSE), {SOURCE}"},
        {**base, "test": "e_form_per_atom", "simulated_value": e_form_true + d, "reference_value": e_form_true,
         "error_abs": d, "reference_source": f"{wid} MP2020-corrected formation energy, {SOURCE}"},
        {**base, "test": "e_above_hull", "simulated_value": each_pred, "reference_value": each_true,
         "error_abs": each_pred - each_true, "reference_source": f"{wid} e_above_hull vs MP PPD (MP2020), {SOURCE}"},
    ])
    payload = {"wbm_id": wid, "formula": relaxed.composition.reduced_formula, "n_atoms": len(relaxed),
               "e_mace": e_mace, "e_dft": e_dft, "de_mev": d * 1000, "each_true": each_true, "each_pred": each_pred,
               "e_form_true": e_form_true, "rejection": rejection, "converged": res["converged"],
               "n_steps": res["n_steps"], "wall_time_s": res["wall_time_s"],
               "spin_caveat": flags["spin_caveat"], "relaxed": relaxed, **job.get("payload_extra", {})}
    store.record_job(SUITE, key, "ok", payload=payload, settings=base["settings"], runtime_s=res["wall_time_s"])
    log.info("%-14s %-14s dE %+8.1f meV/atom  e_hull true %.3f pred %.3f  steps %3d  %.1fs%s", wid,
             relaxed.composition.reduced_formula, d * 1000, each_true, each_pred, res["n_steps"], res["wall_time_s"],
             f"  REJECTED: {rejection}" if rejection else "")


def run(compute: dict, retry_failed: bool = False, limit: int | None = None) -> None:
    if not SUMMARY.is_file() or not INIT_STRUCTS.is_file():
        raise FileNotFoundError(f"WBM files missing in {WBM_DIR} — see README (figshare doi:10.6084/m9.figshare.22715158)")
    tag = settings_tag(compute["device"], compute["dtype"])
    summary = load_summary().set_index("material_id")
    ids = load_sample(summary.reset_index())[: limit or None]
    structs = load_structures(ids)
    done = store.completed_keys(SUITE, retry_failed=retry_failed)
    jobs = []
    for wid in ids:
        key = f"{wid}@{tag}"
        if key in done or wid not in structs:
            continue
        jobs.append({"job_key": key, "wbm_id": wid, "structure": structs[wid], "ref": summary.loc[wid].to_dict(),
                     "device": compute["device"], "dtype": compute["dtype"]})
    perf = core_counts()["performance"]
    big_workers = max(1, perf // 5)
    tiers = [("small", [j for j in jobs if len(j["structure"]) <= LARGE_CELL_ATOMS], compute["workers"], compute["threads_per_worker"]),
             ("large", [j for j in jobs if len(j["structure"]) > LARGE_CELL_ATOMS], big_workers, max(1, perf // big_workers))]
    log.info("OOD: %d sampled WBM structures, %d to relax", len(ids), len(jobs))
    for name, tier_jobs, workers, threads in tiers:
        if tier_jobs:
            for j in tier_jobs:
                j["layout"] = {"tier": name, "workers": workers, "threads_per_worker": threads}
            log.info("OOD %s cells: %d jobs on %d workers x %d threads", name, len(tier_jobs), workers, threads)
            run_pool(relax_job, sorted(tier_jobs, key=lambda j: -len(j["structure"])), workers, threads, on_result=_record)
    print_summary(tag)


# --- analysis ------------------------------------------------------------------------------------

def table(tag: str) -> pd.DataFrame:
    pls = store.load_payloads(SUITE, tag=tag).values()
    rows = [pl for pl in pls if "each_pred" in pl]
    df = pd.DataFrame(rows)
    static = {pl["wbm_id"]: pl["de_static_mev"] for pl in pls if pl.get("kind") == "static"}
    if len(df):
        df["de_static_mev"] = df.wbm_id.map(static)
        # Re-apply the energy guard to stored results so a tightened rule filters them without a re-run.
        df["rejection"] = [compare.recheck(pl.get("rejection"), pl) for pl in rows]
    return df


def score(df: pd.DataFrame) -> dict:
    """Energy / stability metrics over usable (non-rejected) structures."""
    d = df[df["rejection"].isna()] if "rejection" in df else df
    out = {"n": len(d), "n_rejected": len(df) - len(d)}
    if not len(d):
        return out
    de = d["de_mev"].astype(float)
    out.update({"energy_mae_mev": float(de.abs().mean()), "energy_rmse_mev": float(np.sqrt((de ** 2).mean())),
                "energy_mean_signed_mev": float(de.mean()),
                "e_hull_mae_mev": float((d["each_pred"] - d["each_true"]).abs().mean() * 1000),
                "prevalence_stable_0": float((d["each_true"] <= ON_HULL_TOL).mean())})
    for thr in THRESHOLDS:
        out[f"thr{thr}"] = compare.classification_metrics(d["each_pred"] <= thr + ON_HULL_TOL,
                                                           d["each_true"] <= thr + ON_HULL_TOL)
    return out


def _fmt(s: dict) -> str:
    if not s.get("n"):
        return "n=0"
    cls = "  ".join(f"@{t}: P {s[f'thr{t}']['precision']:.2f} R {s[f'thr{t}']['recall']:.2f} "
                    f"Acc {s[f'thr{t}']['accuracy']:.2f} F1 {s[f'thr{t}']['f1']:.2f}" for t in THRESHOLDS)
    return (f"n={s['n']} (rejected {s['n_rejected']})  energy MAE {s['energy_mae_mev']:.1f} meV/atom "
            f"(mean {s['energy_mean_signed_mev']:+.1f}, RMSE {s['energy_rmse_mev']:.1f})  e_hull MAE "
            f"{s['e_hull_mae_mev']:.1f} meV/atom  stable prevalence {s['prevalence_stable_0']:.0%}  {cls}")


def print_summary(tag: str) -> None:
    df = table(tag)
    if df.empty:
        print("No OOD results yet.")
        return
    print(f"\n=== OUT-OF-DISTRIBUTION: WBM unique prototypes, {len(df)} random (seed {SEED}) — settings {tag} ===")
    print(f"{'ALL':<18} {_fmt(score(df))}")
    print(f"{'no spin caveat':<18} {_fmt(score(df[~df.spin_caveat]))}")
    print(f"{'spin caveat':<18} {_fmt(score(df[df.spin_caveat]))}")
    rej = df[df["rejection"].notna()]
    if len(rej):
        print("rejected:", rej[["wbm_id", "formula", "rejection"]].to_dict("records"))
    print("\n--- IN-DISTRIBUTION (Materials Project) for comparison — reported separately ---")
    try:
        from harness.suites import stability, substitution

        sub = substitution.pair_table(tag)
        print(f"MP energy (substitution ctrl, n={len(sub)}): MAE {sub['ctrl_dE_mev'].abs().mean():.1f} meV/atom "
              f"(mean {sub['ctrl_dE_mev'].mean():+.1f})")
        st = stability.target_table(tag)
        m = stability.metrics(st, "a")
        print(f"MP stability mode (a) (n={m['n']}): e_hull MAE {m['mae_ev'] * 1000:.1f} meV/atom  "
              + "  ".join(f"@{t}: P {m[f'thr{t}']['precision']:.2f} R {m[f'thr{t}']['recall']:.2f} "
                          f"Acc {m[f'thr{t}']['accuracy']:.2f}" for t in THRESHOLDS))
    except Exception as exc:  # noqa: BLE001
        print(f"(in-distribution numbers unavailable: {exc})")
    worst = df.reindex(df["de_mev"].abs().sort_values(ascending=False).index).head(10)
    print("\nWorst 10 OOD energy errors:")
    print(worst[["wbm_id", "formula", "n_atoms", "de_mev", "each_true", "each_pred", "spin_caveat", "rejection"]]
          .to_string(index=False, float_format=lambda x: f"{x:.3f}"))
